site_name: Hibernation Operator
docs_dir: content
site_url: https://docs.stakater.com/hibernation-operator-docs
repo_url: https://github.com/stakater/hibernation-operator-docs
edit_uri: blob/main/content/
theme:
  favicon: assets/images/favicon.svg

strict: true
validation:
  links:
    anchors: warn

extra:
  version:
    provider: mike
    default: latest

nav:
  - index.md
  - About:
    - about/key-features.md
    - about/use-cases.md
    - about/benefits.md
  - Architecture:
    - architecture/architecture.md
  - Installation:
    - installation/overview.md
    - installation/openshift.md
    - installation/kubernetes.md
  - Kubernetes Resources:
    - architecture/concepts.md
    - kubernetes-resources/cluster-resource-supervisor.md
    - kubernetes-resources/resource-supervisor.md
  - How-to Guides:
    - installation/setup-CRs.md
  - Integrations:
    - integrations/argocd.md
  - eula.md
  - troubleshooting.md
